self.matrix[13] = ("              ______________                  ")
self.matrix[12] = ("        ,===:'.,            `-._              ")
self.matrix[11] = ("             `:.`---.__         `-._          ")
self.matrix[10] = ("               `:.     `--.         `.        ")        
self.matrix[9]  = ("                 \.        `.         `.      ")
self.matrix[8]  = ("         (,,(,    \.         `.   ____,-`.,   ")
self.matrix[7]  = ("      (,'     `/   \.   ,--.___`.'            ")
self.matrix[6]  = ("  ,  ,'  ,--.  `,   \.;'         `            ")
self.matrix[5]  = ("   `{D, {    \  :    \;                       ") 
self.matrix[4]  = ("     V,,'    /  /    //                       ")
self.matrix[3]  = ("     j;;    /  ,' ,-//.    ,---.              ") 
self.matrix[2]  = ("     \;'   /  ,' /  _  \  /  _  \   ,'/       ")
self.matrix[1]  = ("           \   `'  / \  `'  / \  `.' /        ")
self.matrix[0]  = ("            `.___,'   `.__,'   `.__,'         ")